### ISSUE TITLE
check omission in GLM

### ISSUE THREAD

**Issue by saramortara** [Model-R/modleR#45]
GLM dão muitos valores de NA na omissão, precisa checar de onde vem

**Comment by AndreaSanchezTapia** [comment]
acho que a gente precisa checar essa tabela em geral. que que é threshold e que que é valor e que fique claro.

**Comment by AndreaSanchezTapia** [comment]
agora acho que dá. não é omission mas FNR - vou rodar os exemplos de novo e só reabrimos esta issue se continuar estranho.
