### ISSUE TITLE
reestruturar geo_filt: filtro ambiental e geográfico

### ISSUE THREAD

**Issue by saramortara** [Model-R/modleR#51]
consertar argumento min_distance

**Comment by AndreaSanchezTapia** [comment]
A gente precisa separar o occ thinning que geo_filt faz (e que spThin e [este snippet](https://enmtools.blogspot.com/2015/10/handy-little-snippet-of-r-code-for.html) fazem ) dos fltros ambientais. Acho que geo_filt não vai mudar, não vale a pena implementar spThin por dentro. A ideia é fazer um thinning ambiental? Aqui só estou perguntando pelas presenças. Acho que vou fechar isto e reabrimos se alguém tem o intuito de testar.
