### ISSUE TITLE
evaluate presencenb e absencenb

### ISSUE THREAD

**Issue by diogosbr** [Model-R/modleR#57]
Nos arquivos de evaluate tem as colunas presencenb e absencenb, estas colunas seriam os números de registros utilizados para gerar os modelos de cada partição?
Caso sim, os valores não estão corretos, pois mostram o número de pontos que a partição possui (presença e ausência) e não a quantidade de pontos utilizados.

Por exemplo: 
Um conjunto de dados com 16 pontos de presença e 100 de ausências, em cada partição vai usar 12 pontos de presença e 75 de ausência para treino. Porém, no _evaluate_ vai aparecer 4 para presença e 25 para ausências.

**Comment by saramortara** [comment]
isso vem do evaluate do dismo @np e @na que são 'number of presence points' e 'number of absence points' que vem de fato no número de pontos usados

**Comment by AndreaSanchezTapia** [comment]
Não sei se entendi bem, mas se você quiser o número total ele está nos metadados nas últimas duas colunas, nfinal e nbackfinal.
