### ISSUE TITLE
ROC plot, Variable Contribution and AICc

### ISSUE THREAD

**Issue by geamaro** [Model-R/modleR#74]
Estou tentando ver se há uma forma de obter um gráfico da ROC, os valores de contribuição e permuta para as variáveis (especialmente em modelos MaxEnt) e se é possível calcular o valor do AICc.

No caso do MaxEnt, se o retorno de do_any()  fosse o próprio modelo, seria fácil resolver as primeiras questões. Alguma forma de fazer isso (memo uma indicação de alguma modificação direta no código).

Obrigado!!

**Comment by AndreaSanchezTapia** [comment]
Olá, é uma sugestão muito boa que tentaremos implementar em breve. Basicamente vamos modificar o objeto devolvido pela função para que o usuário tenha acesso aos objetos de interesse criados durante a modelagem.

**Comment by AndreaSanchezTapia** [comment]
O novo parâmetro `write_rda` na função de modelagem (`do_any()`, `do_many()`) permite salvar o objeto .rda com o modelo fittado, o qual permite carregá-lo (com a função `load()`) e utilizar qualquer outra função compatível dentro de R. Vale lembrar que cada rodada de modelagem gera vários modelos fitados, dependendo da partição dos dados, portanto vários objetos .rda serão gerados. O nome do arquivo .rda segue o padrão dos png, com o nome da espécie, o algoritmo e o número de rodada. No entanto, todos estes .rda carregam um objeto nomeado `mod`, portanto ao carregar sucessivamente vários destes objetos dentro do workspace, eles têm de ser renomeados, ou um único objeto `mod`será reescrito.

**Comment by AndreaSanchezTapia** [comment]
Vou considerar resolvida mas fico atenta a qualquer comentário.

**Comment by geamaro** [comment]
Não resolve o caso. O ideal seria ter um objeto S4 dismo::ModelEvuation, por exemplo, com todas as informações resultantes dos ajustes do modelo. Assim seria possível retirar essas informações e obter os retornos necessários. Veja que o ENMEval faz uso dessa funcionalidade e permite esse acesso facilmente. Permanece a sugestão e ter o retorno de do_any() em um objeto.
