### ISSUE TITLE
Error with writing rasters with do_any

### ISSUE THREAD

**Issue by SusanaPallares** [Model-R/modleR#80]
Hello everyone,
I am running the code with the example dataset to try the package before using it with my data. 

The first step works but I get some warnings: 

sdmdata_1sp <- setup_sdmdata(species_name = species[1],
                             occurrences = occs,
                             predictors = example_vars,
                             models_dir = test_folder,
                             partition_type = "crossvalidation",
                             cv_partitions = 5,
                             cv_n = 1,
                             seed = 512,
                             buffer_type = "mean",
                             png_sdmdata = TRUE,
                             n_back = 500,
                             clean_dupl = FALSE,
                             clean_uni = FALSE,
                             clean_nas = FALSE,
                             geo_filt = FALSE,
                             geo_filt_dist = 10,
                             select_variables = TRUE,
                             sample_proportion = 0.5,
                             cutoff = 0.7)

Warning messages:
1: In wkt(obj) : CRS object has no comment
2: In wkt(obj) : CRS object has no comment
3: In RGEOSDistanceFunc(spgeom1, spgeom2, byid, "rgeos_distance") :
  Spatial object 1 is not projected; GEOS expects planar coordinates
4: In wkt(obj) : CRS object has no comment
5: In wkt(obj) : CRS object has no comment
6: In rgeos::gBuffer(spgeom = occurrences, byid = FALSE, width = dist.buf) :
  Spatial object is not projected; GEOS expects planar coordinates

Then I get an error when fitting the models

sp_maxnet <- do_any(species_name = species[1],
                    algorithm = "maxnet",
                    predictors = example_vars,
                    models_dir = test_folder,
                    png_partitions = TRUE,
                    write_bin_cut = FALSE,
                    equalize = TRUE)

maxnet
Ano_exi maxnet run number 1 part. nb. 3
fitting models
projecting the models
evaluating the models
writing evaluation tables
writing raster files
Error in .gd_SetProjectWkt(object, ...) : 
  STRING_ELT() can only be applied to a 'character vector', not a 'closure'
Además: Warning message:
In .gd_SetProjectWkt(object, ...) : NO WKT AVAILABLE FOR PROJ >= 6

Any help would be appreciated. Thank you very much

**Comment by AndreaSanchezTapia** [comment]
Hi Susana it seems as if you had trouble with your raster variables. Could you send a .zip file with example data to  andreasancheztapia@gmail.com?

**Comment by AndreaSanchezTapia** [comment]
We updated the example data and they should work now. We changed their resolution and extent to keep the package light but other raster layers should work as well. Please reinstall and let us know if everything is working.
