### ISSUE TITLE
min_geog_dist >= dist.buf in create_buffer()

### ISSUE THREAD

**Issue by diogosbr** [Model-R/modleR#84]
Hello!

In the `create_buffer ()` function, line 161, returns a warning if `min_geog_dist> = dist.buf in create_buffer ()`. But, if this condition is true, the workflow will break, since the `r_buffer` cutout will not have pixels.
So, I think we could replace the `warning` with a `stop`, so the user should review the informed `min_geog_dist`.

**Comment by AndreaSanchezTapia** [comment]
great! can you file the pull request?

**Comment by diogosbr** [comment]
Ok! 
I did this on the commit [7880ee1](https://github.com/Model-R/modleR/commit/5247509a6dd164fd600a9d7104dda2bf0dd36c05).
