### ISSUE TITLE
erro ao executar o final_model

### ISSUE THREAD

**Issue by annacristina16** [Model-R/modleR#96]
olá, preciso de ajuda! 
ao executar o final_model, a seguinte mensagem de erro aparece:  
Error in .startGDALwriting(x, filename, gdal = options, ...) : 
  formal argument "sources" matched by multiple actual arguments
######
estou utilizando os comandos descritos abaixo:
final_model <- final_model(species_name = unique(sp_input[1]),
            algorithms = NULL, #if null it will take all the algorithms in disk
            models_dir = "./resultados/",
            which_models = c("raw_mean",
                             "bin_mean"),
            consensus_level = 0.5,
            uncertainty = FALSE,
            scale_models=TRUE,
            overwrite = TRUE)
######
existe algum pacote que eu consiga executar corretamente o final_model?

**Comment by AndreaSanchezTapia** [comment]
Oi, esse erro vem do fato que ainda estamos usando o pacote raster para guardar nossos .tif. 
Você poderia instalar a versão de desenvolvimento de raster e me contar se o problema continua, por favor? 

```
install.packages('raster', repos='https://rspatial.r-universe.dev')
```

**Comment by AndreaSanchezTapia** [comment]
:) que bom que funcionou. Vou fechar a issue mas em algum momento (logo) a gente precisa passar para terra.
